/**
 * framework-config.mjs
 * Framework configuration for {CLIENT_NAME}
 * Generated by init-client-repo.mjs — modify only with orchestrator approval.
 *
 * ─── BACKWARD COMPATIBILITY ───────────────────────────────────────────────────
 * If this file is missing from a repo, or any flag is absent, ALL development
 * modes default to TRUE (safest for production quality). Agents must apply this
 * rule: "if missing → true".
 *
 * ─── PROJECT TYPES ────────────────────────────────────────────────────────────
 *   greenfield   — New project from scratch (modes set interactively at init)
 *   brownfield   — Legacy replatforming (modes set interactively at init)
 *   client-repo  — Production, regulated (modes set interactively at init)
 *   microservice — Multi-service coordination (modes set interactively at init)
 *   experimental — POC/spike/research → all modes auto-set to FALSE
 *   local-dev    — Single developer, local only → all modes auto-set to FALSE
 *
 * ─── MODE FLAGS ───────────────────────────────────────────────────────────────
 *   grillMeMode  — orchestrator/decision agents use grill-me skill (Q&A gates)
 *   cavemanMode  — TDD agents use caveman skill (~75% fewer tokens, PRU saver)
 *   tddMode      — enforce RED → GREEN → REFACTOR cycle per implementation layer
 *   bddMode      — BA generates .feature files; RED phase uses them as scaffolding
 *   dddMode      — DDD patterns enforced (aggregates, value objects, domain events)
 *   approvalMode — mandatory when tddMode=false && bddMode=false && dddMode=false
 *
 * ─── YOLO MODE ────────────────────────────────────────────────────────────────
 *   "ne me pose pas de question pas skip les gates" (CTO)
 *   YOLO = grillMeMode:true → grill-me skill replaces formal doc reviews.
 *   All gates (plan-approval.yaml) remain MANDATORY. Nothing is skipped.
 *
 * ─── WORKFLOW BEHAVIOUR ───────────────────────────────────────────────────────
 *   Workflows (.github/workflows/*.workflows.yml) branch based on these flags.
 *   See each workflow's `conditions` section for per-step behaviour changes.
 *   PRU impact: experimental/local-dev saves ~60-75% vs full enterprise config.
 */

export const frameworkConfig = {
  client_name: '{CLIENT_NAME}',

  // ── Project metadata (set at init, drives mode recommendations) ─────────────
  project_metadata: {
    // project_type: greenfield | brownfield | experimental | local-dev | client-repo | microservice
    project_type: 'brownfield',
    // scope: enterprise | mid-market | startup | poc
    scope: 'poc',
    // estimated user story count (drives PRU budget recommendations)
    estimated_stories: 0,
    initialized_at: '{INIT_DATE}',
  },

  // ── Framework internals ──────────────────────────────────────────────────────
  framework: {
    version: '2.0.0',
    source_location: '.github',
    strategy: 'symlink-local-only',
    auto_update: true,
    git_ignored: true,
    never_commit: true,
  },

  // ── Conversation modes (affect agent communication style) ────────────────────
  conversation_modes: {
    // grillMeMode: orchestrator/decision agents use grill-me skill for Q&A validation
    grillMeMode: false,
    // cavemanMode: TDD agents use caveman skill (ultra-compressed, ~75% fewer tokens)
    cavemanMode: true,
  },

  // ── Development modes (affect workflow paths — see *.workflows.yml) ──────────
  development_modes: {
    // tddMode: enforce RED → GREEN → REFACTOR per layer (workflow 05 branches on this)
    tddMode: false,
    // bddMode: BA generates .feature files; workflows 03+05 branch on this
    bddMode: false,
    // dddMode: DDD patterns enforced; workflows 02+05 branch on this
    dddMode: false,
    // approvalMode: auto-derived — true when tddMode=false && bddMode=false && dddMode=false
    approvalMode: true,
  },
};

export default frameworkConfig;
